version: '3'
services:

  apache-container:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    depends_on:
      - mysql
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ''
    depends_on:
      - mysql
  
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_ALLOW_EMPTY_PASSWORD: true
        MYSQL_DATABASE: dbamano
volumes:
  mysql:
